### ISSUE TITLE
Implicit identity conversions on top of collections in foreach

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn#22031]
See https://github.com/dotnet/roslyn/pull/21791#discussion_r137704194

For both languages, we should examine what implicit conversions are exposed on top of collection and whether they are expected.

**Comment by jinujoseph** [comment]
Verify and add more details

**Comment by mavasani** [comment]
Seems like this is still reproing for C#, and we have redundant implicit identity conversion nodes for collection. VB seems to have correct tree. See C# unit test [IForEachLoopStatement_WithList](http://index/?query=IForEachLoopStatement_WithList&rightProject=Roslyn.Compilers.CSharp.Semantic.UnitTests&file=IOperation%5CIOperationTests_IForEachLoopStatement.cs&line=91):

```
Collection: 
    IConversionOperation (TryCast: False, Unchecked) (OperationKind.Conversion, Type: System.Collections.Generic.List<System.String>, IsImplicit) (Syntax: 'list')
      Conversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
      Operand: 
        ILocalReferenceOperation: list (OperationKind.LocalReference, Type: System.Collections.Generic.List<System.String>) (Syntax: 'list')
  ```
