### ISSUE TITLE
IOperation Test Dumper indentation uses 4 instead of 2 sometimes

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn#22559]
see this (https://github.com/dotnet/roslyn/pull/22435/commits/e07a2cfbde6c97d6cca3b236ad516441ea0a6428#r142240694)
 
I see children uses 4 indentation rather than 2 like others? is this intentional?

**Comment by mavasani** [comment]
Also see https://github.com/dotnet/roslyn/issues/22556 for whitespace issues.

**Comment by mavasani** [comment]
Few other formatting issues to address:
1. `IInvocationOperation` dump has a redundant whitespace after open paren: `IInvocationOperation ( void `
2. Locals should be dumped on separate lines, if there are more than one. Current dump contains:
```
IUsingOperation (OperationKind.Using, Type: null) (Syntax: 'using (C c1 ... }')
  Locals: Local_1: C c1
    Local_2: C c2
  Resources: 
```
