### ISSUE TITLE
Move trigger branches to YAML

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn#31767]
This is supported by Azure DevOps now. Here is an example: 

https://github.com/dotnet/arcade-minimalci-sample/blob/master/azure-pipelines.yml#L10

``` yaml
# CI and PR triggers
trigger:
- master

pr:
- master
```

The understanding is that Azure will use the target branch of the PR as the source of truth when deciding if a build should occur or not. Example: if a PR is done to master-vs-deps Azure will look at the YAML in master-vs-deps to see if a trigger exists for that branch.
