### ISSUE TITLE
Microsoft.CSharp.Core.targets(59,5): error on linux.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/roslyn#36616]
I used travis-ci to build project.  
Here is the build configuration:
```yaml
language: csharp
solution: Natasha.sln
mono: none
dotnet: 2.2
dist: xenial
sudo: required

before_install:
  - sudo apt-get install nuget

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

install:
  - dotnet restore

script:
  - dotnet build -c Release
```

Here is the error message: [build--log](https://api.travis-ci.com/v3/job/209616911/log.txt)
You can turn to the bottom few lines.  

`
[39;49m[39;49m[31m/home/travis/.nuget/packages/microsoft.net.compilers/3.1.1/tools/Microsoft.CSharp.Core.targets(59,5): error : Got a SIGABRT while executing native code. This usually indicates [/home/travis/build/dotnetcore/Natasha/Natasha/Natasha.csproj]
[39;49m[39;49m[31m/home/travis/.nuget/packages/microsoft.net.compilers/3.1.1/tools/Microsoft.CSharp.Core.targets(59,5): error : a fatal error in the mono runtime or one of the native libraries  
...................
`  

How can I solve this problem?
